### PR TITLE
Add type-safe model classes for API responses

### PR DESCRIPTION
**Pull request by MathNerd28**
Instead of requiring consumers to parse API response JSON themselves, provide classes that perform this for them. This fixes the note in the README stating that JSON is the only way to access data.

The primary benefit is for accessing the weather data fields, as this approach prevents any developer misspellings or typos by ensuring the weather parameter exists before it can be keyed into the map.

For example, instead of:
```dart
Weather api = ...
Map<String, dynamic> weather = await api.raw_request(...);
num? currentTemperature = weather['current']['temperature_2m'] as num?;
```

... one could write this much more safely:
```dart
Weather api = ...
WeatherResponse weather = await api.request(...);
if (response is WeatherData) {
  num? temperature = response.currentWeatherData[Current.temperature_2m];
} else {
  response as WeatherError;
  // handle error
}
```

So far I have written a sample implementation for the Weather API, let me know if this is worth continuing or if any improvements need to be made.

### CODE REVIEW

**Comment by MathNerd28** [comment]
Forgot to mention, you'll need to do `dart run build_runner build` to generate additional source files before using.

**Comment by neursh** [comment]
The author of Open Meteo stated that they are now using FlatBuffers schema. ([original comment](https://github.com/open-meteo/open-meteo/issues/627#issuecomment-1916602351)).

https://github.com/open-meteo/sdk/blob/main/flatbuffers/weather_api.fbs

I found that they handle this by combining all variables on every time option (daily, hourly, current,...) into one.

We have 4 options:
- Follow their implementation and use FlatBuffers, which is the easiest way, but FlatBuffers is not widely used in Dart scene, or at least I'm not aware of.
- Make our own implementation for every API model like your current scope.
- Based on their implementation, make one big classifier that fits every API model but without the FlatBuffers part.
- None, keep using `raw_request`.

**Comment by kemolumi** [comment]
Open Meteo has FlatBuffer as their main method to use for both performance and provides a strict typing to their API.

They use size prefixed message so we must handle that then read the data.

For example, here's a rough implementation without abstraction for one location:
```dart
final Uint8List flatBytes = (await get(Uri.parse('https://api.open-meteo.com/v1/forecast?hourly=temperature_2m&temperature_unit=celsius&latitude=52.52&longitude=13.41&timeformat=unixtime&timezone=auto&format=flatbuffers'))).bodyBytes;
final int prefixed = BufferContext.fromBytes(flatBytes).buffer.getUint32(0, Endian.little);

print(WeatherApiResponse(flatBytes.sublist(4, 4 + prefixed)).hourly!.variables![0].values);
```

For two locations:
```dart
final Uint8List flatBytes = (await get(Uri.parse('https://api.open-meteo.com/v1/forecast?hourly=temperature_2m&temperature_unit=celsius&latitude=52.52,52.55&longitude=13.41,13.42&timeformat=unixtime&timezone=auto&format=flatbuffers'))).bodyBytes;
final flatBuffer = BufferContext.fromBytes(flatBytes).buffer;
final int firstPrefixed = flatBuffer.getUint32(0, Endian.little);
final int secondPrefixed = flatBuffer.getUint32(firstPrefixed + 4, Endian.little);
print(WeatherApiResponse(flatBytes.sublist(4, 4 + firstPrefixed)).hourly!);
// This is a naive implementation.
print(WeatherApiResponse(flatBytes.sublist(8 + firstPrefixed)).hourly!);
```

The `WeatherApiResponse` is generated using FlatBuffer compiler from the schema file provided by open meteo:
https://github.com/open-meteo/sdk/blob/main/flatbuffers/weather_api.fbs
https://flatbuffers.dev/

You can read more about it here:
https://github.com/open-meteo/sdk

JSON response shouldn't be used in this situation as they're very slow when handles a large amount of data on both consumer and server, I think they uses JSON as an available format solely for demonstration purposes.

We can use the generated typing and return `WeatherApiResponse`, or we could provide another layer of abstraction on top of it and return to consumers.

FlatBuffer branch: [flatbuffer-test](https://github.com/neursh/open-meteo-dart/tree/flatbuffer-test)

Open Meteo author purposes this change for quite a time long ago 😅. ([original comment](https://github.com/open-meteo/open-meteo/issues/627#issuecomment-1916602351))

**Comment by MathNerd28** [comment]
I like the FlatBuffers approach, this library should definitely use the official schema they provide and take advantage of the performance benefits.

One thing I noticed that's missing is API errors, the { error: true, reason: "..." } structure. The other thing I don't like so much is the FlatBuffer schema combines all of the variables into a single enumeration rather than splitting them into Current, Daily, and Hourly like you did.

Both of these could easily be fixed with an intermediate layer of abstraction, so I think that's definitely the way to go.

**Comment by kemolumi** [comment]
That's amazing, I'll try making a generator for the transformation process from FlatBuffer values (fromVariable static function in enum).

**Comment by MathNerd28** [comment]
I wrote a recursive suffix parser in Dart (because I'm not comfortable enough to get anything done in JS), which you can translate if you want and use to implement the switch-case generation.

**Comment by MathNerd28** [comment]
It takes in the parameters to convert and returns an `Index` in the following pseudo-format:

```yaml
variable_1:
  parameter_1:
    property_1: value_1
  parameter_2: {}
variable_2:
  ...
```

Here's a small sample structure:
```yaml
temperature:
  temperature_2m:
    v.altitude: (2)
  temperature_80m:
    v.altitude: (80)
  temperature_1000hPa:
    v.pressureLevel: (1000)
  temperature_2m_max:
    v.aggregation: Aggregation.maximum
    v.altitude: (2)
dew_point:
  dew_point_2m:
    v.altitude: (2)
apparent_temperature:
  apparent_temperature: {}
cloud_cover:
  cloud_cover: {}
  cloud_cover_1000hPa:
    v.pressureLevel: (1000)
cloud_cover_low:
  cloud_cover_low: {}
soil_temperature:
  soil_temperature_0cm:
    v.depth: (0)
  soil_temperature_0_to_7cm:
    (v.depth, v.depthTo): (0, 7)
...
```

**Comment by kemolumi** [comment]
Wow, that surely took some time. Now I feel bad for not contributing much in this one. 🥲

**Comment by kemolumi** [comment]
Thanks for the contributions you've made for the last 2 weeks!

**Pull request merged**
